# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180320_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
