# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180320_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='username',
            new_name='name',
        ),
    ]
