# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180320_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='replystate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
