# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180320_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='replystate',
        ),
    ]
