# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_guestbook_replystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='state',
            field=models.FloatField(default=0),
        ),
    ]
