# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_guestbook_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
